kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: guestbook  
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: guestbook.app.atwiss.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: guestbook-ui
                port:
                  number: 80
